GitHubActions: Replace TTK-ParaView cache with release assets
topology-tool-kit/ttk pull request #661
Opened 2021-09-27 09:18 UTC by pierre-guillou

This PR replaces the cache used in the "test_build" GitHub Actions workflow with release assets.

The last PRs on the TTK repositories showed that the GitHub Actions cache scope is restricted to a branch and PRs that target it. Since the CI is not triggered after the merge but only when PRs are opened, this means that currently no cache is associated with the "dev" branch.

Another workaround would be to enable this workflow on push events on the "dev" branch. However, this might have an impact on forks of the reference repository with "dev" branches, triggering sometimes unwanted CI pipelines. Besides, in case of a cache miss during a PR, a second cache miss would also occur after the merge because the PR-triggered workflow cache is associated to the PR branch, not the "dev" branch. The current version, by using Release Assets instead of cache, solves those two shortcomings.

Enjoy,
Pierre

2021-09-28 07:26 UTC, julien-tierny requested changes

2021-09-28 07:26 UTC, julien-tierny commented on .github/workflows/test.yml
> +        wget https://github.com/pierre-guillou/paraview-ttk/releases/download/5.9.1-headless/ttk-paraview-headless.tar.gz
this asset should be available on `https://github.com/topology-tool-kit/ttk-paraview` instead.
thanks PRing this repository accordingly.

2021-09-28 07:26 UTC, julien-tierny commented on .github/workflows/test.yml
> +        -Uri https://github.com/pierre-guillou/paraview-ttk/releases/download/5.9.1-headless/ttk-paraview-headless.exe
same remark as above.

2021-09-28 07:26 UTC, julien-tierny commented
this looks like low priority.

2021-10-02 17:43 UTC, pierre-guillou commented
Also replaced the ccache cache on Ubuntu & macOS with release assets to further cut down the CI time to about 30/40min (if the manually-generated ccache archives are up-to-date).

Next: investigate sccache for MSVC (for a future PR).

2021-10-14 14:55 UTC, pierre-guillou commented on .github/workflows/test.yml
> +        wget https://github.com/pierre-guillou/paraview-ttk/releases/download/5.9.1-headless/ttk-paraview-headless.tar.gz
Fixed through #669

2021-10-14 14:55 UTC, pierre-guillou commented on .github/workflows/test.yml
> +        -Uri https://github.com/pierre-guillou/paraview-ttk/releases/download/5.9.1-headless/ttk-paraview-headless.exe
idem

2021-10-14 14:56 UTC, pierre-guillou commented
The "check_code" workflow now also uses the ParaView 5.9.1 headless packages.

2021-10-15 06:20 UTC, julien-tierny approved these changes

2021-10-15 06:20 UTC, julien-tierny commented
ok, looks good now.
thanks

2021-10-15 06:20 UTC, merged