Add links to examples documentation
topology-tool-kit/ttk pull request #685
Opened 2021-11-26 10:03 UTC by pierre-guillou

This PR adds HTML links in the doxygen documentation of the VTK layer and in the corresponding XML files to the imageProcessing and the morseSmaleQuadrangulation examples.

This completes https://github.com/topology-tool-kit/ttk-data/pull/88 and https://github.com/topology-tool-kit/ttk-data/pull/93.

This might cause some conflicts with other PRs though...

Enjoy,
Pierre

2021-11-26 11:02 UTC, pierre-guillou commented
Also added persistenceDrivenCompression example (https://github.com/topology-tool-kit/ttk-data/pull/100).

2021-12-02 07:11 UTC, julien-tierny requested changes
could you please resolve the conflicts?
thanks!

2021-12-02 09:43 UTC, pierre-guillou commented
Should be good now

2021-12-02 09:54 UTC, julien-tierny approved these changes

2021-12-02 09:54 UTC, julien-tierny commented
look good, thanks!

2021-12-02 09:54 UTC, merged