Another batch of small fixes
topology-tool-kit/ttk pull request #728
Opened 2022-02-16 12:46 UTC by pierre-guillou

This PR is a collection of small fixes. Among them:
* The Windows CI was referring to my ttk-data fork (typo)
* Removed the WebSocketIO module from the generated TopologyToolKit.h base header, as it would draw the websocket++ library as a package dependency and it's not (yet) packaged on Ubuntu...
* Replaced all instances of `gnu::parallel_sort` with the `PSORT` macro, which does the same thing but factored.
* `CinemaQuery` now filters the input columns to exclude non-scalar columns & columns with a space in their name, in order to prevent SQLite errors.
* `ImplicitTriangulation` preconditions with `ManifoldCheck` in non-kamikaze mode should not return errors any more
* Removed a print in `skeleton` that was dumping the `vertexStars` content in the terminal in the last debug level (the only data structure printed in this module)
* Replaced a Variable-lenght array in `ttkCompactTriangulationPreconditioning` with a `std::array` of fixed size
* Added guards around potential nullptr dereferences in `Octree`
* Other minor things & typos corrections.

Enjoy,
Pierre

2022-02-18 05:38 UTC, julien-tierny commented on core/base/ftmTree/FTMTree_MT.cpp
> +    PSORT(this->threadNumber_)
I'd recommend to rename in the future this macro into `TTK_PSORT`, to make it clear to developers that they can find the definition of the macro within TTK.

2022-02-18 05:49 UTC, julien-tierny commented
ok, thanks for considering my two suggestions about `PSORT` and `PeriodicImplicitTriangulation`.

2022-02-18 05:49 UTC, julien-tierny requested changes
Thanks for considering my 2 remarks.

2022-02-18 05:49 UTC, julien-tierny commented on core/base/implicitTriangulation/ImplicitTriangulation.cpp
> +  return TTK_TRIANGULATION_INTERNAL(getVertexNeighborNumber)(vertexId);
please report the same fix to `PeriodicImplicitTriangulation.cpp`

2022-02-18 05:49 UTC, julien-tierny commented on core/base/ftmTree/FTMTree_MT.cpp
> +    PSORT(this->threadNumber_)
(see my other comments on slack)

2022-02-18 16:43 UTC, pierre-guillou commented on core/base/implicitTriangulation/ImplicitTriangulation.cpp
> +  return TTK_TRIANGULATION_INTERNAL(getVertexNeighborNumber)(vertexId);
No need: PeriodicImplicitTriangulation uses fixed values for all these functions.

2022-02-19 14:19 UTC, julien-tierny approved these changes

2022-02-19 14:19 UTC, julien-tierny commented
alright, looks good!

2022-02-19 14:20 UTC, merged