Nmi ari sim for pr
topology-tool-kit/ttk pull request #905
Opened 2023-01-26 14:00 UTC by atalon-lip6

This PR adds two modules:
NMI-ARI to compare two clusterings
SIM to compare two distance matrices (for example in low and high dimensions).

2023-01-31 08:51 UTC, julien-tierny commented
hi @atalon-lip6 ,
thanks for the PR. can you please fix the fail checks before I proceed to the review?
thanks!

2023-01-31 21:37 UTC, atalon-lip6 commented
> hi @atalon-lip6 , thanks for the PR. can you please fix the fail checks before I proceed to the review? thanks!

Hello! This should be okay now.

2023-02-01 12:09 UTC, julien-tierny requested changes
ok, that looks great and very  polished. thanks!

thanks for considering my few minor remarks.

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +  std::vector<std::vector<int>> &contingencyMatrix,
I believe this parameter should be `const` (it seems to be used in read-only mode).

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +  std::vector<std::vector<int>> &contingencyMatrix,
I believe this parameter should be `const` (it seems to be used in read-only mode).

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +  int nPoint,
this parameter may be set to `const` (to explicitly mark it as read-only).

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +  int nPoint,
this parameter may be set to `const` (to explicitly mark it as read-only).

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +#ifndef TTK_ENABLE_KAMIKAZE
the flag `TTK_ENABLE_KAMIKAZE` is meant to only be set around consistency checks in low-level portions of the code (typically in the directory `core/base`).

in general, `printMsg` calls should be left out of `TTK_ENABLE_KAMIKAZE` code blocks.
then, the message will only be displayed if the object is called with the appropriate debug level.

in this example, I'd suggest to remove the lines 217 to 225 (I guess they're leftovers from the helloworld example)

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.cpp
> +#ifndef TTK_ENABLE_KAMIKAZE
I would remove the `TTK_ENABLE_KAMIKAZE` macro here.
the messages below may be important for the user.

2023-02-01 12:09 UTC, julien-tierny commented on core/base/clusteringMetrics/ClusteringMetrics.h
> +/// TTK Publications.
IEEE Transactions on Visualization and Computer Graphics, 2023.

2023-02-01 12:09 UTC, julien-tierny commented on core/base/distanceMatrixDistorsion/DistanceMatrixDistorsion.cpp
> +#ifndef TTK_ENABLE_KAMIKAZE
same remark as before regarding `TTK_ENABLE_KAMIKAZE`.
I would remove the block line 21 to 29.

2023-02-01 12:09 UTC, julien-tierny commented on core/base/distanceMatrixDistorsion/DistanceMatrixDistorsion.cpp
> +#ifndef TTK_ENABLE_KAMIKAZE
same remark as before about timings (no `TTK_ENABLE_KAMIKAZE` safeguard here).

2023-02-01 12:09 UTC, julien-tierny commented on core/vtk/ttkDistanceMatrixDistorsion/ttkDistanceMatrixDistorsion.cpp
> +#ifndef TTK_ENABLE_KAMIKAZE
I would remove the safeguard `TTK_ENABLE_KAMIKAZE` has this part of the code is not low-level (it is not continuously called by a calling program) and informing the user about a potentially invalid input is useful.

2023-02-01 15:15 UTC, atalon-lip6 commented
I implemented the modifications, this should be good now @julien-tierny

2023-02-02 05:33 UTC, julien-tierny commented
alright, looks good. thanks!

2023-02-02 05:33 UTC, merged