The switch between the legacy and the lts versions of the topological simplification are now done in the ttk layer. Also, fixing the lts module so that each function returns 0 if successful, 1 on errors.
topology-tool-kit/ttk pull request #911
Opened 2023-02-14 10:16 UTC by atalon-lip6

This PR contains two commits.

The first one modifies both the VTK and the TTK layer for the topological simplification. The TopologicalSimplificaiton class is now a container with two members : one object from the legacy implementation (formerly in the TopologicalSimplification class) and one from the lts version. We can set the backend for the new TopologicalSimplification object, which then runs the appropriate algorithm, all in the TTK Layer.

The second was prompted by a note in the code requiring to make lts use the same status return convention as the other ttk modules: return 0 in case of success and something else on errors. This commit fixes this problem for all functions and subfunctions of this module, updating the few places in the other modules which explicitely used lts.

2023-02-15 16:23 UTC, julien-tierny commented
can you please investigate the CI fail?

2023-02-16 14:39 UTC, atalon-lip6 commented
> can you please investigate the CI fail?

I am doing it. Apparently it's a false positive (one uploaded and needed artifact not found), so I am rerunning the tests.

2023-02-16 16:58 UTC, atalon-lip6 commented
> > can you please investigate the CI fail?
> 
> I am doing it. Apparently it's a false positive (one uploaded and needed artifact not found), so I am rerunning the tests.

But there was also something more, the tests are taking ages now. I will have a look at it, some ContourTree computations aborted and done again a lot of times.

2023-02-17 15:55 UTC, julien-tierny commented
> > > can you please investigate the CI fail?
> > 
> > 
> > I am doing it. Apparently it's a false positive (one uploaded and needed artifact not found), so I am rerunning the tests.
> 
> But there was also something more, the tests are taking ages now. I will have a look at it, some ContourTree computations aborted and done again a lot of times.

it seems that this PR is actually breaking the example `states/contourTreeAlignment.pvsm`.
thanks for double-checking this (for instance by running it locally, I suspect it may go in an infinite loop, this is what it looks like it's doing in the CI).

2023-02-18 12:07 UTC, atalon-lip6 commented
> > > > can you please investigate the CI fail?
> > > 
> > > 
> > > I am doing it. Apparently it's a false positive (one uploaded and needed artifact not found), so I am rerunning the tests.
> > 
> > 
> > But there was also something more, the tests are taking ages now. I will have a look at it, some ContourTree computations aborted and done again a lot of times.
> 
> it seems that this PR is actually breaking the example `states/contourTreeAlignment.pvsm`. thanks for double-checking this (for instance by running it locally, I suspect it may go in an infinite loop, this is what it looks like it's doing in the CI).

Indeed, I noticed that. In the end it was a small mistake in the second commit: I missed one replacement to do.
It's all clean now :-)

2023-02-28 12:24 UTC, julien-tierny requested changes
thanks!
please consider my remarks.

2023-02-28 12:24 UTC, julien-tierny commented on core/base/legacyTopologicalSimplification/LegacyTopologicalSimplification.h
> +/// \ingroup base
to add in core/base/topologicalSimplification.

2023-02-28 12:24 UTC, julien-tierny commented on core/base/legacyTopologicalSimplification/LegacyTopologicalSimplification.h
> +    inline void setNumberOfVertices(size_t n) {
to remove.

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalCompression/CMakeLists.txt
> +    legacyTopologicalSimplification
topologicalSimplification

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalCompression/TopologicalCompression.h
> +#include <LegacyTopologicalSimplification.h>
TopologicalSimplification

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalCompression/TopologicalCompression.h
> +    LegacyTopologicalSimplification topologicalSimplification{};
TopologicalSimplification

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
add doxygen documentation

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +    enum TOPO_BACKEND { TOPO_LTS, TOPO_LEGACY };
SIMPLIFICATION_BACKEND

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +          legacyObject_.setNumberOfVertices(
call legacyObject_.preconditionTriangulation() or ltsObject_.preconditionTriangulation()

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +          legacyObject_.setNumberOfVertices(
do the setDebugLevel + setThreadNumber here

2023-02-28 12:24 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +    inline void setBackend(const std::string &arg) {
not with a string but enum

2023-02-28 12:24 UTC, julien-tierny commented on core/vtk/ttkTopologicalSimplification/ttkTopologicalSimplification.cpp
> +    this->setBackend("legacy");
not with a string but enum

2023-02-28 12:35 UTC, julien-tierny requested changes
(added further clarifications)

2023-02-28 12:35 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +      ltsObject_.setDebugLevel(debugLevel_);
move to preconditioning

2023-02-28 12:35 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +      ltsObject_.setThreadNumber(threadNumber_);
move to preconditioning

2023-02-28 12:35 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +      legacyObject_.setDebugLevel(debugLevel_);
move to preconditioning

2023-02-28 12:35 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +      legacyObject_.setThreadNumber(threadNumber_);
move to preconditioning

2023-03-05 12:43 UTC, atalon-lip6 commented on core/base/topologicalCompression/TopologicalCompression.h
> +    LegacyTopologicalSimplification topologicalSimplification{};
It seems to me that this variable is never used.

2023-03-06 14:54 UTC, julien-tierny commented on core/base/topologicalSimplification/TopologicalSimplification.h
> +    enum TOPO_BACKEND { TOPO_LTS, TOPO_LEGACY };
maybe use the PersistenceDiagram style instead (enum declared within the class, simpler)

2023-03-06 14:56 UTC, julien-tierny commented on core/base/topologicalCompression/CMakeLists.txt
> +    legacyTopologicalSimplification
use the legacy instead (based on discussions) because the compression is using specific features.

2023-03-06 14:56 UTC, julien-tierny commented on core/base/topologicalCompression/TopologicalCompression.h
> +#include <LegacyTopologicalSimplification.h>
use the legacy instead (based on discussions) because the compression is using specific features.

2023-03-06 14:56 UTC, julien-tierny commented on core/base/topologicalCompression/TopologicalCompression.h
> +    LegacyTopologicalSimplification topologicalSimplification{};
use the legacy instead (based on discussions) because the compression is using specific features.

2023-03-07 12:23 UTC, julien-tierny commented
alright, looks good. thanks!

2023-03-07 12:23 UTC, merged