Path compression
topology-tool-kit/ttk pull request #939
Opened 2023-05-16 12:47 UTC by rgcmaack

The path compression filter allows to take an input scalar field (vtkDataSet) and compute the ascending and descending Morse segmentations, as well as a Morse-Smale segmentation hash.

2023-05-16 14:30 UTC, julien-tierny commented
Thanks a lot @rgcmaack for this PR!
It seems that it still does not go through the entire set of CI tests (for instance doxygen errors).
Could you address that before we move forward?
Thanks!

2023-05-16 15:22 UTC, rgcmaack commented
It now failed at installing Ubuntu dependencies. Is there something I can do about that? @julien-tierny 
`E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/w/websocketpp/libwebsocketpp-dev_0.8.1-7_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http: [IP: 40.119.46.219 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

2023-05-16 15:46 UTC, julien-tierny commented
that's a github issue (sometimes their VMs have network issues). I re-launched the failed jobs.

2023-06-01 14:23 UTC, julien-tierny requested changes
Alright, thanks a lot @rgcmaack for this great PR.
It looks good to me and ready to be merged, except one tiny detail that bugs (above about the double implementation mono-thread and multi-thread). Thanks for your feedback on that. In principle, I'd argue for only one implementation.
@JonasLukasczyk your thoughts?

2023-06-01 14:23 UTC, julien-tierny commented on core/base/pathCompression/PathCompression.h
> +  } else {
I don't understand why you have a specialized implementation for 1 thread and one for multiple threads.
Is it to improve the performance of the mono-thread version? 

From a maintenance standpoint, it would be really preferable to have only one implementation (i.e. the multi-threaded one). I don't see a case where optimizing mono-thread execution is relevant anymore.

2023-06-01 14:23 UTC, julien-tierny commented on core/base/pathCompression/PathCompression.h
> +#pragma omp parallel num_threads(threadNumber_)
same remark as above.

2023-06-05 11:47 UTC, rgcmaack commented on core/base/pathCompression/PathCompression.h
> +  } else {
The double implementation comes from the issue of guarding everything related to OpenMP/multithreading with "ifdefs". Previous versions needed even more of those guards.

As removing the TTK_ENABLE_OPENMP flag will be another discussion, i will push a single implementation version for now.

2023-06-05 11:54 UTC, julien-tierny commented on core/base/pathCompression/PathCompression.h
> +  } else {
hi @rgcmaack, thanks for your feedback.
I believe you can still have only one implementation and still use `#ifdef TTK_ENABLE_OPENMP`.
See for instance the line 254 of `ScalarFieldCriticalPoints.h`:
https://github.com/topology-tool-kit/ttk/blob/dev/core/base/scalarFieldCriticalPoints/ScalarFieldCriticalPoints.h

2023-06-05 11:55 UTC, julien-tierny commented on core/base/pathCompression/PathCompression.h
> +  } else {
Maybe there is something I do not see which prevents you from using the `#ifdef` as in the above example?

2023-06-05 12:34 UTC, rgcmaack commented
> Alright, thanks a lot @rgcmaack for this great PR. It looks good to me and ready to be merged, except one tiny detail that bugs me (below, about the double implementation, mono-thread VS multi-thread). Thanks for your feedback on that. In principle, I'd argue for only one implementation. @JonasLukasczyk your thoughts?

This came from the time where the implementation was changing rapidly. I just pushed a single implementation version.

2023-06-05 13:30 UTC, julien-tierny commented
that looks like it, yes. thanks.
I'm trying to fix the windows CI now. I'll get back to you when it's done.

2023-06-07 11:41 UTC, julien-tierny commented
alright, looks good!
let's go!

2023-06-07 11:41 UTC, merged