[MPI] Add MPI support to periodic triangulation
topology-tool-kit/ttk pull request #946
Opened 2023-06-19 16:13 UTC by eve-le-guillou

Hi all,

This PR adds MPI support to the periodic triangulation.
This is in two fold:
- Implementation of a periodic ghost generator, to handle the periodicity at the boundaries.
- Implementation of all the MPI related methods of `ImplicitTriangulation` in `PeriodicImplicitTriangulation`.

The periodic ghost generator will add a layer of ghost vertices at the global boundaries, by copying data at the opposite side of the data set. The ghosts can then be treated like the ghosts generated by Paraview\`s `GhostCellsGenerator`.  The algorithm is implemented in the `ttkPeriodicGhostsGeneration` filter, however the filter will be called automatically when switching to a periodic grid using the `ttkTriangulationManager`. Therefore no additional step needs to be taken to execute this filter with MPI.

Both the meta grid and the local grid for the `PeriodicImplicitTriangulation` are `PeriodicImplicitTriangulation` objects. This is useful when the number of processes of the execution is low, and some opposite global boundaries are present on the same process. In this case, periodic ghosts are not created, and the local and meta grids are used to have the proper periodic behavior.

Some MPI methods in `ImplicitTriangulation` and `PeriodicImplicitTriangulation` were factorized in a new abstract  class called `RegularGridTriangulation`.

Here is an example that creates a Wavelet dataset, makes it periodic and then smoothes the scalar field:

    data = Wavelet(registrationName="wavelet1")

    tTKTriangulationManager1 = TTKTriangulationManager(registrationName='TTKTriangulationManager1', Input=data)
    tTKTriangulationManager1.PeriodicityinAllDimensions = 1
    tTKTriangulationManager1.DataArrays = ['RTData', 'vtkGhostType']

    tTKScalarFieldSmoother1 = TTKScalarFieldSmoother(registrationName='TTKScalarFieldSmoother1', Input=tTKTriangulationManager1)
    tTKScalarFieldSmoother1.ScalarField = ['POINTS', 'RTData']
    tTKScalarFieldSmoother1.IterationNumber = 5
    tTKScalarFieldSmoother1.MaskField = ['POINTS', 'RTData']

2023-06-23 10:01 UTC, julien-tierny requested changes
ok, thanks a lot @eve-le-guillou 
the code for the periodic ghost did not look so straighforward in the end but you managed to make this work. congratulations!
I have a few remarks below. Thanks for addressing them

2023-06-23 10:01 UTC, julien-tierny commented on core/base/regularGridTriangulation/RegularGridTriangulation.cpp
> +#include "BaseClass.h"
I don't believe this include is necessary.

2023-06-23 10:01 UTC, julien-tierny commented on core/base/regularGridTriangulation/RegularGridTriangulation.h
> +/// ttk::PeriodicImplicitTriangulation. \sa Triangulation
can you please clarify in the documentation that for the moment, this meta-class only holds an interface for MPI-related features? thanks!

2023-06-23 10:01 UTC, julien-tierny commented on core/base/regularGridTriangulation/RegularGridTriangulation.h
> +/// ttk::PeriodicImplicitTriangulation. \sa Triangulation
(i.e. maybe this interface will be enlarged in the future)

2023-06-23 10:01 UTC, julien-tierny commented on core/base/periodicImplicitTriangulation/PeriodicImplicitTriangulation.cpp
> +  this->metaGrid_->preconditionBoundaryVertices();
I don't believe these 3 lines are necessary.
(if they are, I'd recommand to move them over to the actual `preconditionBoundaryVerticesInternal()`)

2023-06-23 10:01 UTC, julien-tierny commented on core/base/triangulation/Triangulation.h
> +    bool isValid{true};
Could you rename this into `isMPIValid_` (and rename the associated setters/getters)?

2023-06-23 10:01 UTC, julien-tierny commented on core/vtk/ttkIdentifiers/ttkIdentifiers.cpp
> +#ifdef TTK_ENABLE_MPI
what if this filter is run without MPI? 
I couldn't find a non-MPI implementation (maybe I didn't see it)

2023-06-26 08:26 UTC, eve-le-guillou commented on core/base/regularGridTriangulation/RegularGridTriangulation.cpp
> +#include "BaseClass.h"
Indeed, it isn't

2023-06-26 08:26 UTC, eve-le-guillou commented on core/base/periodicImplicitTriangulation/PeriodicImplicitTriangulation.cpp
> +  this->metaGrid_->preconditionBoundaryVertices();
They are not, so I deleted them.

2023-06-26 08:27 UTC, eve-le-guillou commented on core/vtk/ttkIdentifiers/ttkIdentifiers.cpp
> +#ifdef TTK_ENABLE_MPI
I added a non-MPI implementation that simply sets the global ids to the local id. Before that, it would simply do nothing.

2023-06-29 04:11 UTC, julien-tierny approved these changes

2023-06-29 04:14 UTC, julien-tierny commented
hi @eve-le-guillou , thanks a lot for the fixes.

while reading again `ttkIdentifiers.cpp`, I realized that it only generated vertex identifiers. 
I believe we should also generate *cell* identifiers (to make sure we can re-construct unambiguously the global identifiers of simplices of intermediate dimensions in explicit mode).
could you add that up real quick?
thanks!

2023-06-29 04:15 UTC, julien-tierny requested changes
hi @eve-le-guillou , thanks a lot for the fixes.

while reading again ttkIdentifiers.cpp, I realized that it only generated vertex identifiers.
I believe we should also generate cell identifiers (to make sure we can re-construct unambiguously the global identifiers of simplices of intermediate dimensions in explicit mode). could you add that up real quick please?
thanks!

2023-06-30 04:17 UTC, julien-tierny commented
awesome, thanks. let's go!

2023-06-30 04:17 UTC, julien-tierny approved these changes

2023-06-30 04:17 UTC, merged