First commit for Dictionary
topology-tool-kit/ttk pull request #948
Opened 2023-06-29 16:06 UTC by Keanu-Sisouk

Thanks for contributing to TTK!

Before submitting your pull request, please:

- [ ] Review our [Contributor Guidelines](https://github.com/topology-tool-kit/ttk/blob/dev/CONTRIBUTING.md), in particular regarding code formatting (with clang-format) and continuous integration.

- [ ] Please provide a quick description of your contributions below:

Your description here

2023-06-30 14:52 UTC, Keanu-Sisouk commented
Code corrected for format, lint code and warnings checking

2023-10-30 06:11 UTC, julien-tierny commented
Can you please sync to resolve conflicts? Thanks!

2023-10-30 10:39 UTC, Keanu-Sisouk commented
Branch rebased on ttk-dev and conflicts resolved (the numerical loss returned may change a little bit)

2023-10-30 14:57 UTC, Keanu-Sisouk commented
Correcting PersistenceDiagramClustering/PDBarycenter.cpp line 346 for Error in Check-Code and Check-Build

2024-01-22 16:18 UTC, julien-tierny requested changes
hi keanu,
thanks a lot for this PR!
here's a first batch of comments.
- essentially, they are mostly about naming conventions (for variables and functions, some clever sed -- i.e. find/replace -- should do)
- a few clarifications regarding Eigen
- some unnecessary headers to remove
- so signal creation to remove
- comments to remove, etc.
feel free to ping me on slack if you need more info!
thanks :)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/CMakeLists.txt
> +    persistenceDiagram
do you need this?
if so, the name of the class may have to be changed.
(if it is specialized for persistence diagrams, the name of the class should reflect it).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/CMakeLists.txt
> +    persistenceDiagram
maybe you'd need to rename it into something like `PersistentDiagramConstrainedOptimization`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/CMakeLists.txt
> +    persistenceDiagram
or, you make this class more general (and not specialized to persistence diagram). to discuss I guess.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/initDictPersistenceDiagram/InitDictPersistenceDiagram.h
> +  class InitDictPersistenceDiagram : public Debug {
I find the name of the class not very explicit.
Words are usually not abbreviated in TTK.
I'd suggest to change the name of the class (and the related files) to something like `PersistenceDiagramDictionaryInitializer` (`PersistenceDictionaryInitializer`)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionaryDecoding/CMakeLists.txt
> +    persistenceDiagramDistanceMatrix
are all these entries needed? (it's easy to try, just remove these lines and see if it sill works).
I have the impression that the dictionary already depend on the distanceMatrix, so I wonder if these lines are really needed. To try.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.h
> +    void setStep(double factEquiv);
-> `double &factEquiv` (also in the implementation of the function).
use `&` by default

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.h
> +    double stepAtom;
-> `stepAtom_`
for member variables (i.e. member of a class), the convention in ttk is to put an extra `_` at the end of the name (to quickly differentiate those from local variables, defined only within functions)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.cpp
> +    for(size_t i = 0; i < hessianList.size(); ++i) {
can you remind me how the code behaves if Eigen is not installed?
do it still compute correctly?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.cpp
> +// TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
how about these comments?
are there more parts to parallelize?
(if not, simply remove these comments)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.cpp
> +  for(size_t i = 0; i < matchings.size(); ++i) {
are the iterations independent from each other? (in which case OpenMP could be used to parallelize them)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.cpp
> +            std::raise(SIGINT);
what???
please add a nice error message here and do *NOT* ever terminate the process (unless for debug purposes, in which case, please just remove that instruction).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.cpp
> +  // #pragma omp parallel for num_threads(threadNumber_)
what happened here?
didn't it work?
if it didn't work, please remove the comment.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramClustering/PDBarycenter.cpp
> +    double weight = useCustomWeights_ ? (*customWeights_)[j] : 0.0;
shouldn't be 1 (instead of 0) when custom weights are not used?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramClustering/PDClustering.cpp
> +    = first_enrichment ? previous_min_persistence : min_persistence;
can you remind me why this file had to be modified?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramClustering/PersistenceDiagramClustering.h
> +    inline void setTimeLimit(const double tl) {
`const double &tl`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramClustering/PersistenceDiagramClustering.h
> +    std::vector<double> *CustomWeights{};
-> "customWeights_"
(in the ttk convetion, variable names start with a lower case, thanks for fixing other occurences)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramClustering/PersistenceDiagramClustering.h
> +    bool UseCustomWeights{false};
`useCustomWeights_`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/initDictPersistenceDiagram/InitDictPersistenceDiagram.cpp
> +#include <InitDictPersistenceDiagram.h>
I would rename this directory into `persistenceDiagramDictionaryInitializer`.
(same for the corresponding class, i.e. "PersistenceDiagramDictionaryInitializer")

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/InitDictRandomly.cpp
> +#include <InitDictRandomly.h>
I would rename that class into "PersistenceDiagramDictionaryRandomInitializer"

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionaryBorderInitializer.cpp
> +  bool do_min_,
I would remove the last `_` at the end of the variable names, when they are local (same for the following two variables).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionaryBorderInitializer.h
> +                 bool do_min_,
same remark as in the cpp file (no final `_` for local variables)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/initDictPersistenceDiagram/InitDictPersistenceDiagram.h
> +    int Wasserstein{2};
member variable naming convention:
- explicit full names (DeltaLim -> DeltaLimit)
- camelWord (DeltaLimit -> deltaLimit)
- final `_` (deltaLimit_)

same for all the member variables below.
please apply this logic to the other classes

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<ttk::DiagramType> &DictDiagrams,
for the local variables, the convention in ttk is to name them with the so-called "camel wording":
`DictDiagrams` -> `dictDiagrams`.
plus, by convention we also tend to use fully explicit names,
`dictDiagrams` -> `diagramDictionary`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      const std::vector<Matrix> &gradsLists,
`gradientLists`?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      const std::vector<int> &checkerAtomsExt,
thanks for providing a more explicit name

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<std::vector<int>> &projForDiag,
thanks for providing a more explicit name

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<std::array<double, 2>> &projLocations,
thanks for providing a more explicit name

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<std::vector<double>> &vectorForProjContrib,
thanks for providing a more explicit name

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<std::vector<std::array<double, 2>>> &pairToAddGradList,
thanks for providing a more explicit name

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramConstrainedOptimization.h
> +      std::vector<ttk::DiagramType> &DictDiagrams,
see the comments below about local variable names

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/InitDictRandomly.h
> +    void execute(std::vector<ttk::DiagramType> &DictDiagrams,
local var names (cf above)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                 std::vector<ttk::DiagramType> &dictDiagrams,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                 std::vector<double> &lossTab,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                std::vector<ttk::DiagramType> &dictDiagrams,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                std::vector<std::vector<double>> &vectorWeights,
cf above remark about local variable names (explicit)
is it a `perAtomWeightVector`?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                std::vector<double> &lossTab,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                std::vector<std::vector<double>> &histoVectorWeights,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +                std::vector<ttk::DiagramType> &histoDictDiagrams,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    int Wasserstein{2};
syntax for member variable:
`type myMemberVariable_;`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    double Alpha{1.0};
syntax for member variable:
`type myMemberVariable_;`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    double DeltaLim{0.01};
same for all the others below

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.h
> +    double stepAtom;
(... except in the specific case of variables directly manipulated by VTK getters and setters)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void execute(std::vector<ttk::DiagramType> &intermediateDiagrams,
after the declarations of the constructor and destructor, it'd be preferable to order the function declarations in alphabetical order (same for all *h files).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    inline void setUseProgApproach(bool data) {
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    inline void setDos(const bool min, const bool sad, const bool max) {
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    inline void setMinPersistence_(const double data) {
the `_` should be removed.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    inline void setMinPersistence_(const double data) {
-> `const double &data`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    double distVect(const std::vector<double> &vec1,
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +      getMostPersistent(const std::vector<BidderDiagram> &bidder_diags) const;
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +      getMostPersistent(const std::vector<BidderDiagram> &bidder_diags) const;
`bidder_diags` -> `bidderDiagrams`

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeGradientWeights(
isn't it `computeWeightGradient`?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +      std::vector<double> &gradWeights,
cf above remark about local variable names (explicit)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +      const std::vector<ttk::DiagramType> &dictDiagrams,
cf above remark about local variable names (explicit).
same for the other parameters below (+ enforce convention)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeGradientAtoms(
`computeAtomGradient` ?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeDirectionsGradWeight(
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeDirectionsGradAtoms(
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    int initDictionary(std::vector<ttk::DiagramType> &dictDiagrams,
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void gettingBidderDiagrams(
`getBidderDiagrams`?

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    double getMaxPers(const ttk::DiagramType &data);
this function name should be more explicit.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeDirectionsGradWeight(
+ more explicit var names + enforced convention

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void computeDirectionsGradAtoms(
+ more explicit var names + enforced convetion

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +    void setBidderDiagrams(const size_t nInputs,
+ more explicit var names + enforced convention

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.cpp
> +#include <Eigen/Dense>
these 2 Eigen includes do not look necessary.
(the file does not include any eigen function)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionaryDecoding/PersistenceDiagramDictionaryDecoding.h
> +    void execute(std::vector<DiagramType> &dictDiagrams,
more explicit variable name + enforce local variable convention (for all parameters in this function)

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionaryDecoding/PersistenceDiagramDictionaryDecoding.h
> +      const std::vector<std::vector<double>> &vectorWeights,
more explicit variable name + enforce local variable convention

2024-01-22 16:18 UTC, julien-tierny commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.h
> +#pragma once
add doxygen documentation.
at least the doxygen preambule with a proper description of the class (see for instance `core/base/abstractTriangulation/AbstractTriangulation.h`).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/initDictPersistenceDiagram/InitDictPersistenceDiagram.h
> +#pragma once
add doxygen documentation.
at least the doxygen preambule with a proper description of the class (see for instance core/base/abstractTriangulation/AbstractTriangulation.h).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/initDictPersistenceDiagram/InitDictRandomly.h
> +#pragma once
add doxygen documentation.
at least the doxygen preambule with a proper description of the class (see for instance core/base/abstractTriangulation/AbstractTriangulation.h).

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionary/PersistenceDiagramDictionary.h
> +///
add a proper description of the class

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionaryDecoding/PersistenceDiagramDictionaryDecoding.h
> +/// \brief TTK processing package for the computation of a Dictionary
add a proper description of the class.

2024-01-22 16:18 UTC, julien-tierny commented on core/base/persistenceDiagramDictionaryDecoding/PersistenceDiagramDictionaryDecoding.h
> +   * The PersistenceDiagramDictionaryDecoding class provides methods to compute
that comment seems outdated.

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.cpp
> +#include <vtkIntArray.h>
that include does not seem necessary.
please remove all unnecessary includes (i.e. delete the line and see if it still builds)

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionary/ttkPersistenceDiagramDictionary.cpp
> +#include <vtkIntArray.h>
that include does not seem necessary.
please remove all unnecessary includes (i.e. delete the line and see if it still builds)

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionary/ttkPersistenceDiagramDictionary.h
> +  // enum class BACKEND{BORDER_INIT = 0 , RANDOM_INIT = 1 , FIRST_DIAGS = 2};
remove comment if not needed

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +/// \brief TTK processing package for the computation of a Dictionary
include proper class description.

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +  void outputDiagrams(vtkMultiBlockDataSet *output,
in the VTK layer, the function names should probably match VTK's naming convention (`GetOutputDiagrams()`)

2024-01-22 16:18 UTC, julien-tierny commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +  double getMaxPersistence(const ttk::DiagramType &diagram) const;
in the VTK layer, the function names should probably match VTK's naming convention (cf above), plus, make the function name more explicit.

2024-02-05 13:51 UTC, julien-tierny commented
hi keanu, 
I've been running the example that you prepared for ttk-data (https://github.com/topology-tool-kit/ttk-data/pull/151).
During the iterations of the optimization, it seems that the timing for the substeps is incorrect (always reporting 12 seconds, no mater what). for instance:
```
[PersistenceDiagramDictionary] Weight Optimization activated
[PersistenceDiagramDictionary] Atom Optimization activated
[PersistenceDiagramDictionary] Minimum not passed273.783325 ..... [12.000s|100%]
[PersistenceDiagramDictionary]  Epoch 32, loss = 273.783325 ..... [12.000s|100%]
[PersistenceDiagramDictionary] Loss returned 206.159905 at Epoch 15
[PersistenceDiagramDictionary] Complete ...................... [0.029s|12T|100%]
[PersistenceDiagramDictionary] New step multi-scale approach:
[PersistenceDiagramDictionary] Weight Optimization activated
[PersistenceDiagramDictionary] Atom Optimization activated
[PersistenceDiagramDictionary] Loss not decreasing enough87 ..... [12.000s|100%]
[PersistenceDiagramDictionary]  Epoch 23, loss = 290.404787 ..... [12.000s|100%]
[PersistenceDiagramDictionary] Loss returned 251.300186 at Epoch 49
[PersistenceDiagramDictionary] Complete ...................... [0.037s|12T|100%]
[PersistenceDiagramDictionary] New step multi-scale approach:
[PersistenceDiagramDictionary] Weight Optimization activated
[PersistenceDiagramDictionary] Atom Optimization activated
[PersistenceDiagramDictionary] Minimum not passed638.536093 ..... [12.000s|100%]
[PersistenceDiagramDictionary]  Epoch 32, loss = 638.536093 ..... [12.000s|100%]
[PersistenceDiagramDictionary] Loss returned 567.337566 at Epoch 71
[PersistenceDiagramDictionary] Complete ...................... [0.197s|12T|100%]
[PersistenceDiagramDictionary] New step multi-scale approach:
[PersistenceDiagramDictionary] Weight Optimization activated
[PersistenceDiagramDictionary] Atom Optimization activated
[PersistenceDiagramDictionary] Loss not decreasing enough174 .... [12.000s|100%]
[PersistenceDiagramDictionary]  Epoch 24, loss = 1064.678174 .... [12.000s|100%]
[PersistenceDiagramDictionary] Loss returned 1052.556453 at Epoch 108
[PersistenceDiagramDictionary] Complete ...................... [0.542s|12T|100%]
[PersistenceDiagramDictionary] Final step multi-scale approach:
[PersistenceDiagramDictionary] Weight Optimization activated
[PersistenceDiagramDictionary] Atom Optimization activated
^[[B[PersistenceDiagramDictionary]  Epoch 14, loss = 1782.946038 .... [12.000s|1[PersistenceDiagramDictionary] Minimum not passed1645.441462 .... [12.000s|100%]
[PersistenceDiagramDictionary]  Epoch 64, loss = 1645.441462 .... [12.000s|100%]
[PersistenceDiagramDictionary] Loss returned 1603.601491 at Epoch 163
```

also, some undesired debug messages are still visible in the command line:
```
[PersistenceDiagramDictionary] Complete ..................... [95.281s|12T|100%]
[PersistenceDiagramDictionary] Total time ................... [96.087s|12T|100%]
[PersistenceDiagramDictionaryDecoding] %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Atom0
Atom1
Atom2
ClusterID
TimeStep
FILE
[PersistenceDiagramDictionaryDecoding] Computed barycenters .. [2.046s|12T|100%]
```

Thanks for fixing these (tiny) issues.

2024-02-05 14:51 UTC, julien-tierny requested changes, later dismissed
here's a few extra comments after running your state file.
thanks!

2024-02-05 14:51 UTC, julien-tierny commented on paraview/xmls/PersistenceDiagramDictionary.xml
> +      <PropertyGroup panel_widget="Line" label="Input Options">
These are more "Output Options"

2024-02-05 14:51 UTC, julien-tierny commented on paraview/xmls/PersistenceDiagramDictionary.xml
> +        <Property name="AtomNumber_" />
Thanks for listing all the other options here too.
Also:
- please organize and group them by theme
- make the labeling convention more uniform (the first word only starts with a capital)
- remove testing options
- make the labels more explicit
- extend the option documentation (`<Documentation>...</Documentation>`)

2024-02-05 14:51 UTC, julien-tierny commented on paraview/xmls/PersistenceDiagramDictionaryDecoding.xml
> +      <!-- Create a UI group that contains all output parameter widgets (here only one) -->
please add a category "Output Options" (like for the PersistenceDiagramDictionary filter)

2024-02-05 14:51 UTC, julien-tierny commented on paraview/xmls/PersistenceDiagramDictionaryDecoding.xml
> +
Does this filter (at least in principle) depends on some of the parameter values set up during encoding?
(for instance to control the size of the barycenters)
If so, these parameter values should be encoded as field data (and read during decoding)

2026-03-11 15:36 UTC, Keanu-Sisouk commented on core/base/constrainedGradientDescent/CMakeLists.txt
> +    persistenceDiagram
Changed the name of the class according to the suggestion of the comment, also the files altogether were moved to the PersistenceDiagramDictionary folder

2026-03-11 15:37 UTC, Keanu-Sisouk commented on core/base/initDictPersistenceDiagram/InitDictPersistenceDiagram.h
> +  class InitDictPersistenceDiagram : public Debug {
The class was renamed accordingly to the suggestion made in the comment, this file was also moved to the PersistenceDiagramDictionary folder

2026-03-11 15:37 UTC, Keanu-Sisouk commented on core/base/persistenceDiagramDictionaryDecoding/CMakeLists.txt
> +    persistenceDiagramDistanceMatrix
Entries removed from the code

2026-03-11 15:38 UTC, Keanu-Sisouk commented on core/base/constrainedGradientDescent/ConstrainedGradientDescent.h
> +    void setStep(double factEquiv);
Added the reference

2026-03-11 15:39 UTC, Keanu-Sisouk commented on core/vtk/ttkPersistenceDiagramDictionary/ttkPersistenceDiagramDictionary.cpp
> +#include <vtkIntArray.h>
3 entries removed, one was necessary to include

2026-03-11 15:39 UTC, Keanu-Sisouk commented on core/vtk/ttkPersistenceDiagramDictionary/ttkPersistenceDiagramDictionary.h
> +  // enum class BACKEND{BORDER_INIT = 0 , RANDOM_INIT = 1 , FIRST_DIAGS = 2};
Comment removed

2026-03-11 15:39 UTC, Keanu-Sisouk commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +/// \brief TTK processing package for the computation of a Dictionary
Class description updated

2026-03-11 15:40 UTC, Keanu-Sisouk commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +  void outputDiagrams(vtkMultiBlockDataSet *output,
Function name corrected

2026-03-11 15:40 UTC, Keanu-Sisouk commented on core/vtk/ttkPersistenceDiagramDictionaryDecoding/ttkPersistenceDiagramDictionaryDecoding.h
> +  double getMaxPersistence(const ttk::DiagramType &diagram) const;
Function name corrected according to the VTK naming convention

2026-04-27 14:48 UTC, julien-tierny commented
DONE:
[x] ttk-data PR merged
[x] code review

TODO:
[ ] CI
[ ] update example database
[ ] update doxygen documentation

2026-04-30 05:53 UTC, merged