New option for distanceMatrixDistortion: do not normalize the result
topology-tool-kit/ttk pull request #964
Opened 2023-08-28 08:43 UTC by atalon-lip6

We propose here two modifications to the distanceMatrixDistortion class. First at a few locations we correct a spelling mistake: distorTion insted of distorsion.

Secondly, we provide the possibility to compute a non-normalized similarity score. Before, we divided everything by the maximum values for each row such that the final result would lie in [0,1]. With the new options enabled, it lies in [-inf, 1].

2023-08-28 15:21 UTC, julien-tierny requested changes
Thanks a lot Alexandre!
Could you address the two minor points of the review? thanks!

2023-08-28 15:21 UTC, julien-tierny commented on paraview/xmls/DistanceMatrixDistortion.xml
> +        number_of_elements="1"
thanks for adding the option `panel_visibility="advanced"` (this will make the checkbox appear only if the advanced view is triggered, i.e. button with the gear icon)

2023-08-28 15:21 UTC, julien-tierny commented on paraview/xmls/DistanceMatrixDistortion.xml
> +        <Property name="DoNotNormalize" />
This is more of an output option I would say.
You may want to create a new, similar `PropertyGoup` with label "Output options" and put this option in it.

2023-08-29 09:03 UTC, atalon-lip6 commented
> Thanks a lot Alexandre! Could you address the two minor points of the review? thanks!

I made the changes you asked!

2023-08-31 09:05 UTC, julien-tierny commented
wonderful, thanks a lot!

2023-08-31 09:05 UTC, merged